services:
    documentation:
        image: squidfunk/mkdocs-material:9
        container_name: mkdocs
        hostname: mkdocs
        command: serve --dev-addr 0.0.0.0:8000 --config-file /docs/mkdocs.yml --watch-theme
        restart: unless-stopped
        ports:
            - "8000:8000"
        volumes:
            - ./docs:/docs:ro
